In [111]:
import pandas as pd
import numpy as np
from functools import reduce
data=pd.read_csv('./Colleges.csv')
data.head(10)

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1.0,California Institute of Technology,CA,939.0,21%,99/100%,3.0,71%,85%,10.0,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4.0
1,2.0,Rice University,TX,2787.0,24%,89/92%,5.0,68%,89%,19.0,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5.0
2,3.0,Williams College,MA,1985.0,23%,93/93%,8.0,89%,94%,1.0,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26.0
3,4.0,Swarthmore College,PA,1479.0,24%,94/98%,8.0,86%,92%,4.0,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21.0
4,5.0,Amherst College,MA,1618.0,18%,94/92%,9.0,84%,94%,5.0,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38.0
5,6.0,Webb Institute,NY,67.0,42%,100/100%,7.0,79%,83%,39.0,"$8,079","$5,579",20%,100%,"$8,079",100%,"$5,700",1.0
6,7.0,Yale University,CT,5339.0,8%,96/97%,7.0,88%,95%,3.0,"$38,432","$15,729",100%,89%,"$38,432",NaN,"$19,228",53.0
7,8.0,Washington and Lee University,VA,1750.0,31%,89/89%,11.0,86%,89%,30.0,"$30,225","$15,452",99%,87%,"$22,063",31%,"$15,634",9.0
8,9.0,Harvard University,MA,6637.0,11%,90*/90*%,8.0,86%,97%,8.0,"$38,831","$17,456",100%,90%,"$33,201",NaN,"$10,465",46.0
9,10.0,Stanford University,CA,7360.0,13%,93/95%,7.0,77%,93%,6.0,"$38,875","$17,746",100%,86%,"$33,709",NaN,"$15,782",62.0

#### Cleaning the Numeric Attributes

In [135]:
def clean(item):
  if type(item) is float and np.isnan(item):
    return np.nan
  if type(item) is float:
    return item
  if item.find('*')!=-1:
    if item.find('/')!=-1:
      SAT=item[:item.find('*')]
      ACT=item[item.find('/')+1:item.find('*', item.find('*')+1)]
      return max(int(SAT), int(ACT))
    else:
      return int(item[:item.find('*')])
  if item.find('/')!=-1:
    SAT=item[:item.find('/')]
    ACT=item[item.find('/')+1:item.find('%')]
    return max(int(SAT), int(ACT))
  if(item.find('%')):
    return int(item[:item.find('%')])
data['*SAT or ACT']=data['*SAT or ACT'].apply(clean)
data['*SAT or ACT'].fillna(data['*SAT or ACT'].median(), inplace=True)
data.head(20)

<ipython-input-135-56c39b996e42>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['*SAT or ACT'].fillna(data['*SAT or ACT'].median(), inplace=True)

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1.0,California Institute of Technology,CA,939.0,21.0,100.0,3.0,71.0,85.0,10.0,32682.0,10981.0,100.0,93.0,18553.0,15.0,10244.0,4.0
1,2.0,Rice University,TX,2787.0,24.0,92.0,5.0,68.0,89.0,19.0,28350.0,14779.0,100.0,88.0,22418.0,34.0,12705.0,5.0
2,3.0,Williams College,MA,1985.0,23.0,93.0,8.0,89.0,94.0,1.0,36550.0,14737.0,100.0,89.0,33251.0,26.0,12316.0,26.0
3,4.0,Swarthmore College,PA,1479.0,24.0,98.0,8.0,86.0,92.0,4.0,38676.0,17386.0,100.0,85.0,11404.0,2.0,12759.0,21.0
4,5.0,Amherst College,MA,1618.0,18.0,94.0,9.0,84.0,94.0,5.0,38492.0,14453.0,100.0,92.0,33411.0,26.0,11544.0,38.0
5,6.0,Webb Institute,NY,67.0,42.0,100.0,7.0,79.0,83.0,39.0,8079.0,5579.0,20.0,100.0,8079.0,100.0,5700.0,1.0
6,7.0,Yale University,CT,5339.0,8.0,97.0,7.0,88.0,95.0,3.0,38432.0,15729.0,100.0,89.0,38432.0,26.0,19228.0,53.0
7,8.0,Washington and Lee University,VA,1750.0,31.0,89.0,11.0,86.0,89.0,30.0,30225.0,15452.0,99.0,87.0,22063.0,31.0,15634.0,9.0
8,9.0,Harvard University,MA,6637.0,11.0,90.0,8.0,86.0,97.0,8.0,38831.0,17456.0,100.0,90.0,33201.0,26.0,10465.0,46.0
9,10.0,Stanford University,CA,7360.0,13.0,95.0,7.0,77.0,93.0,6.0,38875.0,17746.0,100.0,86.0,33709.0,26.0,15782.0,62.0
10,11.0,Princeton University,NJ,4779.0,11.0,97.0,5.0,91.0,97.0,7.0,40169.0,18325.0,100.0,94.0,40169.0,26.0,12000.0,59.0
11,12.0,Massachusetts Institute of Technology,MA,4178.0,16.0,100.0,6.0,82.0,91.0,2.0,39213.0,19609.0,100.0,85.0,30337.0,26.0,22855.0,82.0
12,13.0,Pomona College,CA,1551.0,23.0,98.0,9.0,83.0,88.0,21.0,38130.0,17411.0,100.0,80.0,35702.0,26.0,15600.0,43.0
13,14.0,Emory University,GA,6302.0,42.0,94.0,7.0,82.0,87.0,15.0,37272.0,19657.0,100.0,73.0,23615.0,19.0,17675.0,54.0
14,15.0,Columbia University,NY,4109.0,12.0,93.0,7.0,83.0,93.0,13.0,39493.0,17778.0,100.0,86.0,39493.0,26.0,15331.0,65.0
15,16.0,Duke University,NC,6206.0,25.0,94.0,11.0,88.0,93.0,11.0,40080.0,19996.0,100.0,80.0,26599.0,6.0,20025.0,68.0
16,17.0,Davidson College,NC,1645.0,34.0,89.0,10.0,89.0,91.0,27.0,34706.0,21455.0,100.0,82.0,28630.0,35.0,13697.0,37.0
17,18.0,Wellesley College,MA,2300.0,47.0,89.0,9.0,84.0,88.0,32.0,37419.0,17526.0,100.0,88.0,32919.0,26.0,15697.0,35.0
18,19.0,Vassar College,NY,2472.0,31.0,93.0,9.0,81.0,87.0,22.0,37870.0,19404.0,100.0,78.0,34669.0,26.0,17170.0,64.0
19,20.0,Haverford College,PA,1105.0,32.0,90.0,8.0,89.0,92.0,20.0,38928.0,17826.0,100.0,90.0,38928.0,26.0,15253.0,66.0

#### Cleaning cost based Attributes

In [140]:
costBased=[]
for attribute in list(data):
  if type(data[attribute][0]) is str and data[attribute][0][0]=='$':
    costBased.append(attribute)
def removeDollarOrComma(item):
  print(item)
  if type(item) is float and np.isnan(item):
    return np.nan
  item.strip()
  item=item[1:]
  item=float(''.join(item.split(',')))
  return item
for attribute in costBased:
  data[attribute]=data[attribute].apply(removeDollarOrComma)
  data[attribute].fillna(data[attribute].median(), inplace=True)
data.head(102)
# data.isnull()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1.0,California Institute of Technology,CA,939.0,21.0,100.0,3.0,71.0,85.0,10.0,32682.0,10981.0,100.0,93.0,18553.0,15.0,10244.0,4.0
1,2.0,Rice University,TX,2787.0,24.0,92.0,5.0,68.0,89.0,19.0,28350.0,14779.0,100.0,88.0,22418.0,34.0,12705.0,5.0
2,3.0,Williams College,MA,1985.0,23.0,93.0,8.0,89.0,94.0,1.0,36550.0,14737.0,100.0,89.0,33251.0,26.0,12316.0,26.0
3,4.0,Swarthmore College,PA,1479.0,24.0,98.0,8.0,86.0,92.0,4.0,38676.0,17386.0,100.0,85.0,11404.0,2.0,12759.0,21.0
4,5.0,Amherst College,MA,1618.0,18.0,94.0,9.0,84.0,94.0,5.0,38492.0,14453.0,100.0,92.0,33411.0,26.0,11544.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,98.0,Rensselaer Polytechnic Institute,NY,5139.0,70.0,92.0,17.0,48.0,75.0,84.0,39200.0,22360.0,90.0,74.0,28411.0,45.0,24590.0,94.0
98,99.0,Sarah Lawrence College,NY,1226.0,40.0,79.0,6.0,51.0,66.0,94.0,42121.0,22847.0,94.0,73.0,33610.0,26.0,14864.0,89.0
99,100.0,The George Washington University,DC,10328.0,40.0,72.0,14.0,62.0,73.0,98.0,40240.0,25866.0,94.0,56.0,29916.0,25.0,0.0,96.0
100,NaN,NaN,NaN,NaN,39.5,88.0,NaN,76.0,84.0,NaN,37345.5,18706.5,100.0,78.0,28337.0,26.0,15753.5,NaN
101,NaN,NaN,NaN,NaN,39.5,88.0,NaN,76.0,84.0,NaN,37345.5,18706.5,100.0,78.0,28337.0,26.0,15753.5,NaN

#### Cleaning other Rates

In [128]:
rateBased=[]
for attribute in list(data):
  if type(data[attribute][0]) is str and data[attribute][0][-1]=='%':
    rateBased.append(attribute)
def removePercent(item):
  print(item)
  if (type(item) is str and item[0].isalpha()) or (type(item) is float and np.isnan(item)):
    return np.nan
  item.strip()
  item=item[:-1]
  return float(item)
for attribute in rateBased:
  data[attribute]=data[attribute].apply(removePercent)
  data[attribute].fillna(data[attribute].median(), inplace=True)